version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-web
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: my-secret-pw
      DB_NAME: mydatabase

volumes:
  db_data:
